### GET request to example server
GET localhost:8080/book/

###

POST localhost:8080/book/
content-type: application/json

{
  "title": "Book 1",
  "author": "6e98bf58-0331-4248-9e03-2a2d898b5ef5",
  "category": "620a710e-9b83-4991-af6a-622a2d212273",
  "publicationDate": "13-06-2024 15:42:30",
  "isbn": "1234567890",
  "price": 100.0,
  "pages": 101,
  "resume": "This is a book about something interesting",
  "summary": "This is a book about something interesting"

}
